# Generated by Django 4.2.7 on 2023-11-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_catgory_options_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
